### PR TITLE
Added support for file globs in source_directories.

### PR DESCRIPTION
**Pull request by ypid**
`source_directories_glob` can be used to enable glob support (defaults to
disabled). Let me know what needs to be changed (option names or other stuff) for this patch to get accepted.

### CODE REVIEW

**Comment by witten** [comment]
Great idea.

Can you see any reason not to just glob unconditionally? That way, a user can get the benefits of globbing simply by specifying a path containing a "*", without having to also set a boolean option to enable the feature.

**Comment by ypid** [comment]
Not sure. Maybe users have `*` in there file names. I guess we could enable it by default.

**Comment by witten** [comment]
Yeah, I think it's reasonable to say "*" always means glob, especially if it's documented as such.

**Comment by ypid** [comment]
All right. Can you merge my other PRs so that I can rebase to them and updated this one? (I intend to change this parm to boolean as well).

**Comment by witten** [comment]
All merged.

IMO, you can simply drop the `source_directories_glob` flag entirely (boolean or otherwise) and default to always globbing. One less value to configure that way.

**Comment by ypid** [comment]
Changing it to default has a the side effect removing not existing source_directories from the list. `python -c 'from glob import glob; print(glob("not existing"))'`. Borg would otherwise complain about non existing files. Should I change it to include non existing files and let attic/borg handle it?

**Comment by witten** [comment]
Ah, good point. To deal with the non-existent directory case, what do you think of checking if a particular `glob()` call returns an empty list. And if so, erroring. That might look something like:

```
expanded_sources = [glob(x) for x in sources]
if [] in expanded_sources:
    raise ValueError('oops')
flattened_sources = list(chain.from_iterable(expanded_sources))
```

That way, you'd catch both the case of specifying a literal directory that doesn't exist, and of specifying a glob path that doesn't resolve to anything.

**Comment by ypid** [comment]
I updated the PR just now. I was going with just passing non existing files to the backend and let it deal with that.

**Comment by witten** [comment]
Awesome.. That makes sense as well.

**Comment by witten** [comment]
Note that I altered the test in cf545ae93a26bfb2ed023c2407f09d6601ee761a to mock out the glob() call, so it isn't subject to what's present on the filesystem during the test.

**Pull request merged**
